# -*- coding: utf-8 -*-
"""HappinessWorldReport_Analyzation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hn2z3a28nGEaGqeFw5SZbgWbmLPcXGxr
"""

import pandas as pd
df = pd.read_csv('world-happiness-report-2021.csv')
df1= pd.read_csv('world-happiness-report.csv')

df.head()

df1.head()

import matplotlib.pyplot as plt
import matplotlib.gridspec as gs
import seaborn as sns

top_5 = df.sort_values(by='Ladder score', ascending=False).head(5)
plt.figure(figsize=(8, 4))
sns.barplot(x='Ladder score', y='Country name', data=top_5, palette='magma')
plt.title('Top 5 Countries in Happiness Index (2021)')
plt.xlabel('Ladder Score')
plt.ylabel('Country Name')
plt.xlim(0, 8)
plt.gca().invert_yaxis()
plt.show()

bottom_5 = df.sort_values(by='Ladder score', ascending=True).head(5)
plt.figure(figsize=(8, 4))
sns.barplot(x='Ladder score', y='Country name', data=bottom_5, palette='cividis')
plt.title('Bottom 5 Countries in Happiness Index (2021)')
plt.xlabel('Ladder Score')
plt.ylabel('Country Name')
plt.xlim(0, 8)
plt.gca().invert_yaxis()
plt.show()

average_happiness_by_region = df.groupby('Regional indicator')['Ladder score'].mean().reset_index()
average_happiness_by_region = average_happiness_by_region.sort_values(by='Ladder score', ascending=False)
plt.figure(figsize=(14, 8))
sns.barplot(x='Regional indicator', y='Ladder score', data=average_happiness_by_region, palette='cividis')
plt.title('Average Happiness Score by Regional Indicator (2021)')
plt.xlabel('Regional Indicator')
plt.ylabel('Average Ladder Score')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import numpy as np
df = pd.read_csv('world-happiness-report-2021.csv')
region_counts = df['Regional indicator'].value_counts()
plt.figure(figsize=(10, 6))
plt.pie(region_counts, labels=region_counts.index, colors=sns.color_palette('Set3'), autopct='%1.1f%%', )
plt.title('Distribution of Countries by Regional Indicator (2021)')
plt.show()

df = pd.read_csv('world-happiness-report-2021.csv')
plt.figure(figsize=(10, 6))
sns.regplot(x='Healthy life expectancy', y='Ladder score', data=df, scatter_kws={'alpha':1})
plt.scatter(x=67.401, y=5.985, color='red', s=50, label='Thailand')
plt.title('Relationship between Happiness Index and Healthy Life Expectancy (2021)')
plt.xlabel('Healthy Life Expectancy')
plt.ylabel('Ladder Score')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.regplot(x='Logged GDP per capita', y='Ladder score', data=df, scatter_kws={'alpha':1})
plt.scatter(x=9.805, y=5.985, color='red', s=50, label='Thailand')
plt.title('Relationship between Logged GDP per capita and Happiness Index (2021)')
plt.xlabel('Log GDP per capita')
plt.ylabel('Ladder score')
plt.grid(True)
plt.legend()
plt.show()

df = pd.read_csv('world-happiness-report-2021.csv')
df1 = pd.read_csv('world-happiness-report.csv')
top_5_countries_2021 = df.sort_values(by='Ladder score', ascending=False).head(5)['Country name'].tolist()
countries_to_compare = top_5_countries_2021 + ['Thailand']
df1_filtered = df1[df1['Country name'].isin(countries_to_compare)].copy()
plt.figure(figsize=(12, 6))
sns.lineplot(data=df1_filtered, x='year', y='Life Ladder', hue='Country name')
plt.title('Happiness Index Over Time: Top 5 Countries vs. Thailand')
plt.xlabel('Year')
plt.ylabel('Life Ladder Score')
plt.grid(True)
plt.legend(title='Country')
plt.show()